### ISSUE TITLE
Tach fails in Windows when building exclusion paths, because it does not handle backslash

### ISSUE THREAD

**Issue by aawilson** [gauge-sh/tach#326]
Running tach with an exclusions in Windows (Powershell, presumably also in cmd.exe) produces an error like the following:

```
Failed to build regex pattern for excluded path:
C:\users\aawilson\projects\someproject\.*__pycache__
regex parse error:
    C:\users\aawilson\projects\someproject\.*__pycache__
      ^^
error: unrecognized escape sequence
```
I don't know enough about the usage of the built regex to know if it will be sufficient to escape the backslashes here, since the tach.toml may specify them with solidus it is probably necessary to normalize path separators at various points.

**Comment by emdoyle** [comment]
Thanks for raising this! Will take a look and address this in the next release.

**Comment by aawilson** [comment]
It doesn't, the actual pattern in the .toml is .*__pycache__ and has nothing to escape, the rest is coming from whatever you're using in Rust to get the cwd.

**Comment by emdoyle** [comment]
@aawilson I don't have a Windows machine easily accessible to test, but version `0.12.0` should resolve this issue on Windows. Could you let me know if upgrading fixes the issue?

**Comment by aawilson** [comment]
Sorry for the slow response, I was on vacation. This appears to have resolved the issue, thanks a million for quick action here.

**Comment by aawilson** [comment]
I did play around with more of the functionality and there may be a cousin to this issue still lurking. I'm able to run "tach report" on a path within my project in my WSL container, but not from PowerShell, receiving this error:
```
Report failed: Filesystem error: No matching source root found for filepath: "\\\\?\\C:\\users\\aawilson\\projects\\someproject\\some\\path"
```

**Comment by emdoyle** [comment]
> I did play around with more of the functionality and there may be a cousin to this issue still lurking. I'm able to run "tach report" on a path within my project in my WSL container, but not from PowerShell, receiving this error:
> 
> ```
> Report failed: Filesystem error: No matching source root found for filepath: "\\\\?\\C:\\users\\aawilson\\projects\\someproject\\some\\path"
> ```

Thanks for reporting! I'll take a look at this soon. If you get a sec, would you mind reposting this as a separate issue?
